config/routes.rb
Rails.application.routes.draw do

  # get '/hunches/:id' => 'hunches#show', as: :hunch

  # get '/categories/:id' => 'categories#show'
  # get '/categories' => 'categories#index'

  resources :hunches do
    resources :line_items
  end

  resources :categories

  get '/users/portfolio' => 'users#portfolio'

  resources :users

  get '/cart' => 'carts#show', as: 'cart'

  # post '/line_item/:hunch_id/add' => 'line_items#create'


  root to: 'pages#homepage'

  # get '/hunches/:hunch_id/add' => 'users#add_cart' as: :cart

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # Define your own paths?




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user, optional: true

  has_many :line_items

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :hunches
end

app/models/hunch.rb
class Hunch < ApplicationRecord
  belongs_to :category

  has_many :line_items

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :hunch
  belongs_to :cart
end

app/models/user.rb
class User < ApplicationRecord

has_secure_password

has_one :cart

  # has_many :hunches   # hunches table will need user_id

  validates :email, presence: true,
  uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :fetch_user
  #What is this doing ^^
end

def check_if_logged_in
  if @current_user.nil?
    flash[:error] ='You must be logged in to view this page!'
    redirect_to login_path
  end
end



private

  def fetch_user
    if session[:user_id].present?
      @current_user = User.find_by id:
      session[:user_id]
    end

    session[:user_id] = nil unless
    @current_user
    #What is going on?
  end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :check_if_logged_in
  def index
  end

  def show
  end

  def edit
  end

  def new
  end

  def destroy
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
    @category = Category.find params[:id]
  end
  
end

app/controllers/hunches_controller.rb
class HunchesController < ApplicationController
  def show
    @hunch = Hunch.find params[:id]
  end

  def index
  end


end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def new

  end

  def create


    cart = Cart.find_or_create_by(user_id:@current_user.id)

    # get all line items for cart
    # line_items = cart.line_items

    # check if any of hunch_ids in the cart match the hunch_id in params[:hunch_id]

    # LineItem.where(cart_id: 16)

    line_items = LineItem.where(cart_id: cart.id)


     if line_items.where(hunch_id: params[:hunch_id]).present?

          line_itemz = line_items.where(hunch_id: params[:hunch_id]).first
          line_itemz[:quantity] += params[:line_item][:quantity].to_i
          line_itemz.save
        else
          new_line = LineItem.new(line_item_params)
          new_line.hunch_id = params[:hunch_id]
          new_line.cart_id = cart[:id]
          new_line.save
     end

    # if there's a match, just update the line_item with new quantity

    # no match, create new line item (need params[:hunch_id] and cart_id)

    #
    #
    # if params[:line_item_id].present?
    #   @line_item = LineItem.find(params[:cart_id]).find(params[:hunch_id])
    # else
    #   @line_item = LineItem.new line_item_params
    #   item.cart = cart
    #   item.hunch_id = params[:hunch_id]
    #   item.save
    # end
    #

    # cart = Cart.find_or_create_by(user: @current_user)
    #
    # item = LineItem.new line_item_params
    # item.cart = cart
    # item.hunch_id = params[:hunch_id]
    # item.save

    # Add a new line item to our existing cart, via the line_items association
    # cart.line_items.new line_item_params

    redirect_to cart_path   # '/cart'

  end

  def edit
  end

  def update
  end

  def index
  end

  def show
  end

  def destroy
  end

  private

  def line_item_params
    params.require(:line_item).permit(:quantity)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def homepage
    @categories = Category.all
    # raise 'hell'


  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create

    user = User.find_by email: params[:email]
    
    if user.present? && user.authenticate(params[:password])
      #successful login
      #create a cookie to store a session,
      # and keep track of the user ID

      session[:user_id] = user.id

      redirect_to root_path
    else
      flash[:error] = "Invalid username or password"
      redirect_to login_path
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create

   user = User.new(user_params)
   if params[:file].present?
     req = Cloudinary::Uploader.upload(params[:file])
     user.image = req["public_id"]
   end
   user.save
   redirect_to user_path user
  end

  def edit
    @user = User.find params[:id]

  end

  def update
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      user.image = req["public_id"]
    end
    user.update_attributes(user_params)
    user.save

    redirect_to user_path(user)
  end

  def Portfolio
  end

  def show
    # @user = User.find params[:id]

  end

  def destroy
    User.destroy params[:id]
    redirect_to root_path
  end

  def add_cart
    hunch = Hunch.find params[:id]
      if hunch.present? && !@current_user.hunches.ids.index(hunch.id)
        @current_user.hunches << hunch
      else
        flash[:error] = "Unable to add hunches to cart"
      end
      redirect_to hunch

  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  #securtity
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hunches_helper.rb
module HunchesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
<h1>Carts#index</h1>
<p>Find me in app/views/carts/index.html.erb</p>

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<h1>Carts#show</h1>
<p>Find me in app/views/carts/show.html.erb</p>

<%# raise 'hell' %>
<% @current_user.cart.line_items.each do |i| %>
  <%= i.quantity %> x <%= i.hunch.name %><br>
<% end %>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

<% @category.hunches.each do |hunch| %>
  <%= link_to hunch.name, hunch_path( hunch ) %><br>
<% end %>

app/views/hunches/index.html.erb
<h1>Hunches#index</h1>
<p>Find me in app/views/hunches/index.html.erb</p>

app/views/hunches/show.html.erb
<h1>Hunches#show</h1>
<p>Find me in app/views/hunches/show.html.erb</p>

<%= @hunch.name %>

<hr>



<%= form_for [@hunch, LineItem.new] do |f|%>

<%= f.label :quantity %>
<%= f.text_field :quantity, class:"form-control" %>

<%= f.submit 'Add' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Consultio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="icon" href="https://tinyurl.com/y99rphq6">
  </head>

  <body>
    <div class="navbar-overlay" class="container">
      <nav>
        <ul class="navbar-nav">
          <img src="https://cdn.rawgit.com/Samudabamu/consultio/master/app/assets/images/inspect/cc-samu/Page%201/Home/logo.svg" alt="">
        <li>
          <% if @current_user.present? %>
          <a href="/users/<%= @current_user.id %>/edit"><%= @current_user.name %></a>
          <% else %>
          <a href="/login" class="glyphicon glyphicon-user"></a>
          <% end %>
        </li>
      </ul>
        <div>
          <% if @current_user.present? %>
            <%= link_to 'Logout', login_path, method: :delete %>
          <% end %>
        </div>
      </nav>
    </div>

    <%= yield %>

  </body>
</html>

app/views/line_items/create.html.erb
<h1>LineItems#create</h1>
<p>Find me in app/views/line_items/create.html.erb</p>

app/views/line_items/destroy.html.erb
<h1>LineItems#destroy</h1>
<p>Find me in app/views/line_items/destroy.html.erb</p>

app/views/line_items/edit.html.erb
<h1>LineItems#edit</h1>
<p>Find me in app/views/line_items/edit.html.erb</p>

app/views/line_items/index.html.erb
<h1>LineItems#index</h1>
<p>Find me in app/views/line_items/index.html.erb</p>

app/views/line_items/new.html.erb
<h1>LineItems#new</h1>
<p>Find me in app/views/line_items/new.html.erb</p>

app/views/line_items/show.html.erb
<h1>LineItems#show</h1>
<p>Find me in app/views/line_items/show.html.erb</p>

app/views/line_items/update.html.erb
<h1>LineItems#update</h1>
<p>Find me in app/views/line_items/update.html.erb</p>

app/views/pages/homepage.html.erb
<!DOCTYPE html>

  <head>
    <meta charset="utf-8">
    <title>Consultio-Consultious</title>
    <link href="css/business-frontpage.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300i" rel="stylesheet">
  </head>
  <body>

    <header class="business-header">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h1 class="text-center"></h1>
          </div>
        </div>
      </div>
    </header>

    <div class="container">
      <div class="row">
        <div class="col-sm-8">
          <h2>Want to make some dough?..</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A deserunt neque tempore recusandae animi soluta quasi? Asperiores rem dolore eaque<img src="app/assets/images/inspect/cc-samu/Page 1/Low Risk/logo.svg" alt=""> vel, porro, soluta unde debitis aliquam laboriosam. Repellat explicabo, maiores!</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis optio neque consectetur consequatur magni in nisi, natus beatae quidem quam odit commodi ducimus totam eum, alias, adipisci nesciunt voluptate. Voluptatum.</p>
          <p>
            <a class="btn btn-success btn-lg" href="#">Discover success! &raquo;</a>
          </p>
        </div>
        <div class="col-sm-4">
          <h2>Try Contact Us</h2>
          <address>
            <strong>Towers Pseudo</strong>
            <br>13 Iznop Street
            <br>Camana Bay, 26748
            <br>Cayman Islands
          </address>
          br
          <address>
            <abbr title="Phone">P:</abbr>
            (+1) 949 7000
            <br>
            <abbr title="Email">E:</abbr>
            <a href="mailto:#">Sam@Consultio.io</a>
          </address>
        </div>
      </div>

      <div class="row">
        <% @categories.each do |category| %>
          <div class="col-sm-4 my-4">
            <div class="card">
              <div class="card-body">
                <%= link_to category_path(category) do %>
                  <%= image_tag "http://placehold.it/300x200" %>
                <% end %>
                <ul>
                  <li><h4 class="card-title">
                  <%=category.investment_type%></h4>
                    <ul class="dropdown">
                      <li>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus.</p>
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center"> &copy; Consultio-Consultious 2018</p>
      </div>
    </footer>

  </body>
</html>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<%= flash[:error] %>
<!-- How does the error helper work -->


<%= form_tag login_path, {class: "form-horizontal"} do %>

<div class="form-group">
  <div class="col-sm-3 col-md-offset-4">
    <fieldset>
  <%= label_tag :email %>
  <%= email_field_tag :email,"", class:"form-control" %>
    </fieldset>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-3 col-md-offset-4">
    <fieldset>
      <%= label_tag :password  %>
      <%= password_field_tag :password,"", class:"form-control" %>
    </fieldset>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-6 col-md-offset-5">
    <%= submit_tag 'Login', class:"btn btn-primary btn-lg"  %>
  </div>
</div>

<%= link_to 'Create', "/users/new" %>

<% end %>

app/views/users/_form.html.erb
<% if flash[:errors] %>
<strong>Please correct the following errors:</strong>
<ol>
  <% flash[:errors].each do |e| %>
    <li><%= e %></li>
  <% end %>
</ol>
<% end %>


<%= form_for @user, html: {class:"form-horizontal", multipart: true} do |f| %>

<div class="form-group">
  <div class="col-sm-4 col-md-offset-4">
    <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
    </fieldset>
  </div>
</div>

<div class="form-group">
    <div class="col-sm-4 col-md-offset-4">
    <fieldset>
    <%= f.label :email %>
    <%= f.text_field :email, class:"form-control" %>
    </fieldset>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-3 col-md-offset-4">
  <fieldset>
  <%= f.label :password %>
  <%= f.password_field :password, class:"form-control" %>
  </fieldset>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-3 col-md-offset-4">
  <fieldset>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class:"form-control" %>
  </fieldset>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-6 col-md-offset-4">
    <fieldset>
      <%= f.label :image %>
      <%= f.cl_image_upload :image, class:"form-control" %>
    </fieldset>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-6 col-md-offset-4">
    <%= f.submit 'Submit', class:"btn btn-primary btn-lg" %>
  </div>
</div>

<% end %>

app/views/users/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= render partial: 'form' %>

app/views/users/new.html.erb
<h1 class='col-md-offset-4'>Sign Up</h1>

<%= render partial: 'form' %>

app/views/users/portfolio.html.erb
<h1>Portfolio Placeholder</h1>

app/views/users/show.html.erb
<h2><em><%= @user.name %></em>
<h2><em><%= @user.email %></em>



<%= cl_image_tag @user.image%>


<%= link_to 'Edit', "/users/#{@user.id}/edit" %>

<%= link_to 'Delete', user_path(@user.id), method: :delete %>